# Numpy Module in Python

#### Dont forget to pip install numpy 

In [2]:
#Import module
import numpy as np

### Create numpy array

In [3]:
data = [1,2,3,4,5]
arr = np.array(data)
arr

array([1, 2, 3, 4, 5])

In [6]:
arr2 = np.array([76,12,16])
arr2

array([76, 12, 16])

In [8]:
#Creating multidimensional array
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Accessing and Changing elements

In [10]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# Access the element
print(arr[0,2])

3


In [16]:
# Access the row 
print(arr[0,:])

[1 2 3]


In [17]:
# Acces the column
print(arr[:,2])

[3 6 9]


In [24]:
# arr[x:y:i,a:b:j]
# x:y represents rows from x to y including x
# a:b represents columns from a to b including a
# [x:] or [a:] represents from x or a to the end
# [:x] or [:a] represents from beginning to the x or a excluding x/a
# [:] represents all over the row or column
# i or j represents steps
print(arr[0:2,1:])
print()
print(arr[:1,1:])

[[2 3]
 [5 6]]

[[2 3]]


In [26]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr2[1,::2])

[6 8 0]


In [28]:
# Replace
print(arr2)
arr2[0,2] = 20
print(arr2)

[[ 1  2 20  4  5]
 [ 6  7  8  9  0]]
[[ 1  2 20  4  5]
 [ 6  7  8  9  0]]


### Creating array full of a number

In [32]:
# Creating array full of zeros
arr = np.zeros((2,3)) # 2 rows 3 columns also the parametre must be a tuple
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [33]:
# Creating array full of ones
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
# Creating array full of the number you choose
arr = np.full((2,3),17) # (2,3) is the tuple contains row and column info, 17 is the number to fill the array
arr

array([[17, 17, 17],
       [17, 17, 17]])

In [38]:
# Also full_like method is being used for the fill the array with a spesific number
arr = np.array([1,2,3])
np.full_like(arr,4)

array([4, 4, 4])

In [40]:
# Creating array full of random numbers between (0,1)
arr = np.random.rand(3,3) # 3,3 is the number of rows and columns
arr

array([[0.71031437, 0.51375737, 0.52835358],
       [0.77272626, 0.64710093, 0.38165836],
       [0.39412689, 0.40707614, 0.63230469]])

In [53]:
# Creating array full of random integers and spesific shape
arr = np.random.randint(3,7, size = (2,2)) # random between (3,7) including 3 but not 7, shape of the array is (2,2)
arr

array([[3, 5],
       [4, 6]])

In [56]:
# Creating array full of between spesific numbers
arr = np.arange(1,50,2) # from 1 to 50. 50 not including. 2 is step number
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [57]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr = np.arange(1,11,5)
arr

array([1, 6])

In [64]:
# Creating idendity matrix
arr = np.eye(4,4) # 4,4 is the shape of the array
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
# Creating array full of random numbers but Gaussian Distribution
arr = np.random.randn(10)
arr

array([-0.95485185, -0.46165424,  0.00732536,  2.25286743,  0.3746788 ,
        0.99662501, -0.18762689,  1.04755935,  0.19558092,  1.25390956])

In [74]:
# Creating array full of numbers that are between spesifics numbers and x equal pieces
arr = np.linspace(0,10,5) # from 0 to 10 and 5 equal pieces
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Operations

In [81]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr)
print(arr - 2) 

[1 2 3 4 5 6 7 8 9 0]
[-1  0  1  2  3  4  5  6  7 -2]


In [82]:
print(arr)
print(arr + 5)

[1 2 3 4 5 6 7 8 9 0]
[ 6  7  8  9 10 11 12 13 14  5]


In [83]:
print(arr)
print(arr * 3)

[1 2 3 4 5 6 7 8 9 0]
[ 3  6  9 12 15 18 21 24 27  0]


In [84]:
print(arr)
print(arr / 2)

[1 2 3 4 5 6 7 8 9 0]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 0. ]


In [85]:
print(arr)
print(arr ** 2)

[1 2 3 4 5 6 7 8 9 0]
[ 1  4  9 16 25 36 49 64 81  0]


In [87]:
arr = np.array([1,1,1])
arr2 = np.array([3,2,1])
arr3 = arr + arr2
arr3

array([4, 3, 2])

### Useful methods

In [92]:
arr = np.random.randint(1,100, size = (1,10))
arr

array([[81, 30, 61, 68, 46, 59, 30, 34, 17, 69]])

In [93]:
arr.min() # find min value

17

In [94]:
arr.max() # find max value

81

In [96]:
arr = np.array([1,2,3,4,5])
arr.sum() # sum of the array

15

In [99]:
arr = np.random.randint(1,100, size = (1,10))
arr

array([[51, 80, 37, 10, 15, 61,  3, 40, 99, 53]])

In [100]:
arr.argmax() # Find the index of the max value

8

In [101]:
arr.argmin() # Find the index of the min value

6

In [103]:
arr.mean() # Mean of the array

44.9

In [105]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
arr.reshape(1,9) # Reshape the array 1 is rows 9 is columns

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [116]:
arr = np.random.randint(1,50,size = (1,15))
arr

array([[41,  7, 32, 22, 22, 13, 18, 44, 22, 29, 31, 33, 35, 44, 22]])

In [119]:
arr.sort() # Sorting the array
arr

array([[ 7, 13, 18, 22, 22, 22, 22, 29, 31, 32, 33, 35, 41, 44, 44]])

In [131]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate((arr1, arr2)) # Concatenate the arrays, array parameter should be a tuple
arr3

array([1, 2, 3, 4, 5, 6])

In [136]:
# Copy the array
a = np.array([1,2,3])
b = a # When we make equal a and b
# b and a represents the same array
# So when we change a or b
# It affects both of them
print(b)
b[0] = 2
print(b)
print(a)

[1 2 3]
[2 2 3]
[2 2 3]


In [141]:
a = np.array([1,2,3])
b = a.copy()
# When we use the copy method
# It creates another array that same of a
# So a and b don't represent the same array anymore
# When we change one of them
# It doesn't affect the other one
print(a)
print(b)
b[0] = 2
print("***")
print(a)
print(b)

[1 2 3]
[1 2 3]
***
[1 2 3]
[2 2 3]
