## NUMPY TUTORIAL

#### NumPy is a math library that allows us to make scientific calculations quickly. Numpy arrays are similar to python lists, but are more useful than python lists in terms of speed and functionality.


In [1]:
import numpy as np

####  Single-dimensional Numpy Array

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
type(a)

numpy.ndarray

#### Multi-dimensional Numpy Array

In [4]:
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

#### Note :The reason we use Numpy instead of the list is because Numpy is less memory and faster.

### Numpy.dtype

#### Dtype is an object that defines the type of items in the array.

In [5]:
array=np.array([14,55,66])
array

array([14, 55, 66])

In [6]:
array.dtype

dtype('int32')

In [7]:
array=np.array(["one","two","three"])
array

array(['one', 'two', 'three'], dtype='<U5')

In [8]:
array.dtype

dtype('<U5')

### Numpy.ndim

#### It helps us find the size of the array.

In [9]:
array=np.array([[1,2,3],[4,5,6]])

In [10]:
array.ndim # Since the output is 2, it is a two-dimensional array.

2

### Numpy.shape

#### The elements of the shape tuple give the lengths of the corresponding array dimensions.

In [11]:
array=np.array([[1,2,3],[9,8,6]])
array

array([[1, 2, 3],
       [9, 8, 6]])

In [12]:
array.shape # ( N x M ) N rows and M columns ie 2 rows and 3 columns.

(2, 3)

###  Numpy.reshape 

#### Changes the number of rows and columns of the array.

In [13]:
array=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array # 1 x 10 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
array.reshape(10,1) # 10 x 1

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [15]:
array.reshape(5,2) # 5 x 2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

###   Numpy.size 

#### The total number of elements of the array.

In [16]:
array=np.array([[112,155,182],[1494,28,1453]])
array

array([[ 112,  155,  182],
       [1494,   28, 1453]])

In [17]:
array.size

6

###  Numpy.arange 

#### Returns a numpy array containing the numbers up to the end value, starting from the specified start value and increasing the number of steps each time.

#### General use:  np.arange (start, end, number of steps)  
#### Note :  The number of steps is 1 by default and start default is 0.

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [20]:
np.arange(5,20,3)

array([ 5,  8, 11, 14, 17])

###  Numpy.itemsize 

#### The size in bytes of each element of the array.

In [21]:
array=np.array([5,6,8])
array

array([5, 6, 8])

In [22]:
array.itemsize

4

### Numpy.linspace

#### Returns evenly spaced numbers in a given range.

In [23]:
array=np.linspace(1,3,10)
array  # Returned 10 evenly spaced numbers between 1 and 3.

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [24]:
array=np.linspace(0,5,14)
array 

array([0.        , 0.38461538, 0.76923077, 1.15384615, 1.53846154,
       1.92307692, 2.30769231, 2.69230769, 3.07692308, 3.46153846,
       3.84615385, 4.23076923, 4.61538462, 5.        ])

### Numpy.min

#### Finds the minimum in Array.

In [25]:
array=np.arange(1,14,3)
array

array([ 1,  4,  7, 10, 13])

In [26]:
array.min()

1

### Numpy.max 

#### Finds the maximum in Array.

In [27]:
array=np.arange(1,53,14)
array

array([ 1, 15, 29, 43])

In [28]:
array.max()

43

###  Numpy.sum

#### Collects the elements in Array.

In [29]:
array=np.arange(1,43,11)
array

array([ 1, 12, 23, 34])

In [30]:
array.sum()

70

#### Axis concept in Numpy.

#### If axis=0 , columns

#### If axis=1 , row

In [31]:
array=np.array([[12,13,14],[1,2,3],[4,6,8]])
array

array([[12, 13, 14],
       [ 1,  2,  3],
       [ 4,  6,  8]])

In [32]:
array.sum()

63

In [33]:
array.sum(axis=0)

array([17, 21, 25])

In [34]:
array.sum(axis=1)

array([39,  6, 18])

### Numpy.zeros

#### This function returns a matrix of 0s with the specified row and column.

In [35]:
array=np.zeros((3,4))
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

###  Numpy.ones

#### This function returns a matrix of 1 with the specified row and column.

In [36]:
array=np.ones((3,5))
array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Numpy.eye

#### A function that allows us to create a unit matrix of specified dimensions.

In [37]:
array=np.eye((3))
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Numpy.concatenate

#### It serves to combine arrays.

In [38]:
array1=np.array([1,2,3,4])
array2=np.array([6,9,2,8])
concatenate_array=np.concatenate([array1,array2])
concatenate_array

array([1, 2, 3, 4, 6, 9, 2, 8])

###  Mathematical operations with Numpy

In [39]:
array1=np.arange(1,6)
array1

array([1, 2, 3, 4, 5])

In [40]:
array2=np.arange(8,13)
array2

array([ 8,  9, 10, 11, 12])

In [41]:
array1+array2

array([ 9, 11, 13, 15, 17])

In [42]:
array1-array2

array([-7, -7, -7, -7, -7])

In [43]:
array1*array2

array([ 8, 18, 30, 44, 60])

In [44]:
array1/array2

array([0.125     , 0.22222222, 0.3       , 0.36363636, 0.41666667])

In [45]:
array2**array1

array([     8,     81,   1000,  14641, 248832], dtype=int32)

In [46]:
array=np.array([5,1,8,2])

In [47]:
array.sum()

16

In [48]:
array.prod() # multiplication

80

In [49]:
array.mean()

4.0

In [50]:
array.var() # variance

7.5

In [51]:
array.std() # standard deviation

2.7386127875258306

In [52]:
sorted(array)

[1, 2, 5, 8]

###  Special functions with Numpy

In [53]:
array=np.array([(1,2,3),(3,4,5,)])
array

array([[1, 2, 3],
       [3, 4, 5]])

In [54]:
np.sqrt(array)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.        , 2.23606798]])

In [55]:
np.std(array)

1.2909944487358056

In [56]:
np.exp(array)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [57]:
np.log(array)

array([[0.        , 0.69314718, 1.09861229],
       [1.09861229, 1.38629436, 1.60943791]])

In [58]:
array1 = np.arange(1,4)
array1

array([1, 2, 3])

In [59]:
array2=np.arange(5,8)
array2

array([5, 6, 7])

In [60]:
np.dot(array1,array2) # product of matrices

38

### Array indexing 

In [61]:
array=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
array[0] # First row

array([1, 2, 3, 4])

In [63]:
array[0][0] # First element in the first row

1

In [64]:
array[:,0:1] # All columns of rows 0 to 1.

array([[1],
       [5],
       [9]])

In [65]:
array[1,0:1] # First elemnt of rows 0 to 1.

array([5])

In [66]:
array[:,1:4] # All columns of rows 1 to 4.

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [67]:
array[1:2,:]  # All rows of columns 1 to 2.

array([[5, 6, 7, 8]])